### ISSUE TITLE
Button variants not getting applied

### ISSUE THREAD

**Issue by sirmathays** [selemondev/nuxt-ui-vue#109]
**Describe the bug**
Assigning a variant to a Button does not do anything.

**To Reproduce**
1. Assign variant `outline` (or `ghost`/`soft`/`link`) to UButton component 
    - e.g. `<UButton variant="outline">Button</UButton>` in any `.vue` template
3. See that no outline variant has been applied

**Expected behavior**
When assigning `variant="outline"` to the Button component, I'm expecting to see the Button have the outlined style shown in NuxtUI docs.

**Screenshots**
<img width="159" alt="image" src="https://github.com/selemondev/nuxt-ui-vue/assets/37704147/72d4ae32-1d56-4935-8895-47b96d2fb3cc">
![image](https://github.com/selemondev/nuxt-ui-vue/assets/37704147/8cefc66e-44a7-4ea8-8f3a-e56f8c6ec537)

**Additional context**
Version: nuxt-ui-vue ^0.0.9

**Comment by sirmathays** [comment]
Ahhh, I see now that variants are called intents here :) Apologies!

**Comment by selemondev** [comment]
> Ahhh, I see now that variants are called intents here :) Apologies!

No worries 👍
