### ISSUE TITLE
Cannot import composables

### ISSUE THREAD

**Issue by cuiyajie** [selemondev/nuxt-ui-vue#131]
any support for composables? like defineShortcuts...

**Comment by selemondev** [comment]
As of Nuxt UI Vue v1.0.1-beta.1, you can now be able to import the `defineShortcuts`, `useCopyToClipboard`, `useShortcuts` and `useToast` composables.

**Comment by cuiyajie** [comment]
Great job. I like nuxt ui a lot, but we has built a stable workflow in our project, so we cannot use nuxt at all. But I want to use the nuxt UI. So lucky to find this project. Thanks a lot.
