### ISSUE TITLE
nuxtlabsTheme resolve error when use vite build

### ISSUE THREAD

**Issue by cuiyajie** [selemondev/nuxt-ui-vue#144]
I refer nuxtlabasTheme like `import nuxtLabsTheme from 'nuxt-ui-vue/dist/theme/nuxtlabsTheme`. but github ci builder will throw error 
```
[vite]: Rollup failed to resolve import "nuxt-ui-vue/dist/theme/nuxtlabsTheme" from "/home/runner/work/b3d-frontend/b3d-frontend/web/src/ui/theme.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
```
I build this well in local, but github ci builder always throw error through tried other vite config.

I found same case here: [https://github.com/vitejs/vite/issues/7312](https://github.com/vitejs/vite/issues/7312)

So, can we change the export style of nuxtlabsTheme like `export  { default as nuxtlabsTheme } from '@/theme/nuxtlabsTheme'` in `index.ts`? or same question have you met? how to solve it?

Thanks a lot. Best wishes to you.

**Comment by selemondev** [comment]
Hey @cuiyajie , sorry for not replying back. Were you able to solve this issue?
