### ISSUE TITLE
Failed resolve of `UIcon` in `USelect` component

### ISSUE THREAD

**Issue by sirmathays** [selemondev/nuxt-ui-vue#162]
**Describe the bug**
`USelect` component fails to resolve `UIcon` that is used in the component. Causes a warn message in browser console:

```
[Vue warn]: Failed to resolve component: UIcon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

**To Reproduce**
Add `USelect` component to your project and this will occur.

**Expected behavior**
No Vue warn

**Additional context**
I think the issue is as simple as that there's no `UIcon` imported in `USelect` component.

**Version**
1.0.1-beta.9

**Comment by selemondev** [comment]
Thanks @sirmathays for creating this issue. The issue has now been resolved as of Nuxt UI Vue V1.0.2-beta.1 . A re-write will soon happen that will see the release of Nuxt UI Vue V2.0 which will have all the components, bug fixes and will be in sync with Nuxt UI.
