### ISSUE TITLE
Questions about your workflow and plan for the future

### ISSUE THREAD

**Issue by ManUtopiK** [selemondev/nuxt-ui-vue#90]
Really cool ! Thanks a lot for all this work !

I use nuxt in many projects, and a build web extension with https://github.com/antfu/vitesse-webext
I plan to rewrite some projects with nuxtlabs/ui, and the web extension. Your repo is just what I need :)

I want to know about your workflow.
How do you follow the nuxtlabs/ui developement ? Do you watch every new commit on nuxtlabs/ui, or have you automatized some stuffs ? Do you plan to match exactly the same architecture and component ? And of course, will you follow all update made in nuxtlabs/ui ?

Thanks again.

**Comment by selemondev** [comment]
You're welcome, @ManUtopiK . The plan is to regularly update nuxt-ui-vue after each nuxtlabs-ui release but major issues will be resolved immediately.

**Comment by ManUtopiK** [comment]
Great news !
The release of nuxtlabs/ui is currently [v2.7.0](https://github.com/nuxtlabs/ui/releases/tag/v2.7.0) and your repo is v0.0.3.
It will be nice to write somewhere (in the README.md ?) the version or commit of nuxtlabs/ui it match.

**Comment by selemondev** [comment]
Yeah, that sounds like a great idea.

**Comment by ManUtopiK** [comment]
The dream come true :ok_hand: 
Thanks a lot!
