### ISSUE TITLE
Npm package name

### ISSUE THREAD

**Issue by TechAkayy** [selemondev/nuxt-ui-vue#91]
As it's very early days, would be great to have the npm package sync with the name as `nuxt-ui-vue`. 

It's not taken yet on npm, and would be easy for new users to install easily, when the name sync with the npm package name.

The reason why nuxtlabs/ui didn't change their package name is probably because they existed long before it was made open-source - more details here.. https://github.com/nuxtlabs/ui/issues/538#issuecomment-1682070895

But, there might be a reason for your to keep it as *labs, if you want to retain the coupling with the upstream. But, naming a package as nuxtlabs might raise the assumption that it's one of nuxtlabs project, no harm there, but it's just cleaner to be simpler.

**Comment by selemondev** [comment]
@TechAkayy, this issue has been resolved: https://github.com/selemondev/nuxt-ui-vue/issues/92#issue-1856561175
