### ISSUE TITLE
Migration issues from nuxt-ui to nuxt-ui-vue

### ISSUE THREAD

**Issue by TechAkayy** [selemondev/nuxt-ui-vue#95]
Here is my first attempt in trying to replace @nuxthq/ui with nuxt-ui-vue in my nuxt app. 

Here is a online demo of the original nuxt ui repo - https://pg-nuxtui.netlify.app/, github - https://github.com/pinegrow/pg-nuxtui

**Reproduction with `nuxt-ui-vue`:**
https://github.com/TechAkayy/pg-nuxtui-vue

Few issues: 
1. I had to comment-out UAvatar component in my HeroSection.vue as I was getting some `Image is not defined` error. 
2. I had my own safelisting logic already, and used it in place of nuxtlabs/ui module's `ui > safelistColors` options. But for some reason, my palette colors are getting ignored. 
3. Nuxtlabs/ui uses the iconify's unocss format with the `i-` prefix. I installed @unocss/nuxt and other packages, but the icons are not getting working. 

Thank you for this great effort. Will play it with it more.

**Comment by TechAkayy** [comment]
I also had to include the below to externalize fsevents, wondering if it was due to this package, I didn't had to do it with nuxt-ui

```
vite: {
    //...
    optimizeDeps: { exclude: ["fsevents"] },
}
```

**Comment by selemondev** [comment]
1. `nuxt-ui-vue` is meant to be used in a Vue 3 project and not in a Nuxt 3 project.

2. In regards to icons, you have the flexibility to copy and paste icons directly from the [Iconify](https://icones.netlify.app/) library. However, there's a distinction in how icons are utilized between `nuxt-ui` and `nuxt-ui-vue`. While `nuxt-ui` enables you to download icon sets from Iconify, `nuxt-ui-vue` provides the convenience of copying icon names from the Iconify library, regardless of the icon set.

**Comment by TechAkayy** [comment]
Thank you for the clarifications 🙂

**Comment by cuiyajie** [comment]
@selemondev , Can I use my own iconset created by iconfiy in nuxt-ui-vue?
